### PR TITLE
Try to import full tensorflow before tflite-runtime.

### PR DESCRIPTION
**Pull request by gmsoft-tuxicoman**
Allow loading tflite if the complete tensorflow package has been installed.

### CODE REVIEW

**Comment by gmsoft-tuxicoman** [comment]
There is still a problem with the requirements. If I keep the tflite_runtime requirement, the module won't load because that dependency is not satisfied.

I don't know if it can be made extra or conditional.

**Comment by JarbasAl** [comment]
I like this change, but i have concerned about dropping the requirement, anything installing the plugin without pinning tflite separately will suddenly stop working on new installs

At very least warning in readme are needed

@NeonDaniel any thoughts on this?

**Comment by NeonDaniel** [comment]
Could we put tflite in an optional extra? Then you could decide at install time `pip install precise_lite_runner` or `precise_lite_runner[tflite]`. Then the plugin can still pin a proper (optional) tflite version.

**Comment by gmsoft-tuxicoman** [comment]
I have dropped the requirement in setup.py, not in requirements.txt. This should allow pip to still pull tflite-runtime.
It doesn't hurt if pip pulls it since the code will try to import full tensorflow first (since it's apparently faster) and then tflite.

**Comment by JarbasAl** [comment]
pip reads setup.py not requirements.txt. setup.py itself usually reads requirements.txt but this is not done in all packages yet

i think we can add 2 new optional exras `lite` and `full` under extras require, and then specify tensorflow in full. 

so to install this package one would do either `pip install precise_lite_runner[full]` or `pip install precise_lite_runner[lite]`

the readme should reflect this and probably have a note about full performing faster (saw a link flying by in the chats about this)

**Pull request merged**
